-- Supabase SQL Editor で実行してください

-- メインのタスクテーブル
create table tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  memo text default '',
  done boolean not null default false,
  done_at text,
  prio int not null default 1,
  task_date date not null,
  carry_from text,
  carry_reason text,
  created_at timestamptz not null default now()
);

-- 分割タスク（サブタスク）
create table subtasks (
  id bigint generated by default as identity primary key,
  task_id bigint not null references tasks(id) on delete cascade,
  text text not null,
  memo text default '',
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- 課題
create table issues (
  id bigint generated by default as identity primary key,
  task_id bigint not null references tasks(id) on delete cascade,
  text text not null,
  memo text default '',
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- インデックス（日付ごとの取得を高速化）
create index idx_tasks_date on tasks(task_date);

-- Row Level Security（個人利用なので全員アクセス可にする）
alter table tasks enable row level security;
alter table subtasks enable row level security;
alter table issues enable row level security;

create policy "allow all tasks" on tasks for all using (true) with check (true);
create policy "allow all subtasks" on subtasks for all using (true) with check (true);
create policy "allow all issues" on issues for all using (true) with check (true);
